credentials:
  usernames:
    thiago:
      email: thiagobluhm@gmail.com
      name: Thiago Bluhm
      password: '********'

    maria:
      email: maria@empresa.com
      name: Maria Silva
      password: '********.'

cookie:
  name: xtracta_login
  key: ***********  # 🔒 altere isso
  expiry_days: 1

preauthorized:
  emails: []
